ALTER TYPE "Language" ADD VALUE IF NOT EXISTS 'JA';
ALTER TYPE "Language" ADD VALUE IF NOT EXISTS 'AR';
ALTER TYPE "Language" ADD VALUE IF NOT EXISTS 'KO';
ALTER TYPE "Language" ADD VALUE IF NOT EXISTS 'ZH';
ALTER TYPE "Language" ADD VALUE IF NOT EXISTS 'RU';
